baseURL = 'https://asynet.es/'
locale = 'es-es'
#languageCode = "es-ES"
title = 'Asynet - Servicios IT para tu empresa'
theme = "blowfish"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Servicios"
url = "/servicios/"
weight = 2

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 3

[params]
#description = "Asynet Enterprise Services es una empresa de servicios informáticos especializada en soluciones de tecnología de la información para empresas. Ofrecemos una amplia gama de servicios, incluyendo consultoría, desarrollo de software, soporte técnico y gestión de infraestructura IT. Nuestro objetivo es ayudar a las empresas a optimizar sus operaciones y mejorar su eficiencia a través del uso de la tecnología."
colorScheme = "blowfish"
#favicon = "assets/favicon.ico"
defaultAppearance = "dark"
defaultBackgroundImage = "img/background.svg"
defaultFeaturedImage = "assets/img/featured.svg"
defaultSocialImage = "assets/logo.png"
showSocial = true
showSocialInHeader = true

[[params.social]]
name = "LinkedIn"
url = "https://www.linkedin.com/company/asynet/"
icon = "linkedin"

[[params.social]]
name = "Twitter"
url = "https://twitter.com/asynetes"
icon = "twitter"

#[author]
#name = "Asynet Enterprise Services"
#image = "assets/logo.png"
#headline = "Soluciones IT para tu empresa"

#keywords = [
#    "servicios informáticos",
#    "consultoría IT",
#    "desarrollo de software",
#    "soporte técnico",
#    "gestión de infraestructura IT",
#    "tecnología de la información",
#    "soluciones IT",
#    "optimización de operaciones",
#    "eficiencia empresarial",
#]
theme = 'ananke'
theme = 'ananke'
