baseURL = 'https://asynet.es/'
locale = 'es-es'
title = 'Asynet Enterprise Services'
theme = "blowfish"

[params]
description = "Asynet Enterprise Services es una empresa de servicios informáticos especializada en soluciones de tecnología de la información para empresas. Ofrecemos una amplia gama de servicios, incluyendo consultoría, desarrollo de software, soporte técnico y gestión de infraestructura IT. Nuestro objetivo es ayudar a las empresas a optimizar sus operaciones y mejorar su eficiencia a través del uso de la tecnología."
#author = "Asynet Enterprise Services"
#keywords = [
#    "servicios informáticos",
#    "consultoría IT",
#    "desarrollo de software",
#    "soporte técnico",
#    "gestión de infraestructura IT",
#    "tecnología de la información",
#    "soluciones IT",
#    "optimización de operaciones",
#    "eficiencia empresarial",
#]
colorScheme = "blowfish"
favicon = "favicon.ico"
#defaultAppearance = "dark"
showSocial = true

[params.header]
showLogo = true
showSocial = true

[[params.social]]
name = "LinkedIn"
url = "https://www.linkedin.com/company/asynet/"
icon = "linkedin"

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Servicios"
url = "/servicios/"
weight = 2

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 3
